# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_summary',
            field=models.CharField(default='', max_length=255, verbose_name='Category Summary'),
        ),
    ]
