# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_category_category_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='robotics', unique=True),
            preserve_default=False,
        ),
    ]
