# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='he', unique=True),
            preserve_default=False,
        ),
    ]
