# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course_video',
            field=models.URLField(default='https://www.youtube.com/watch?v=yXNpP-qXdwg', verbose_name='Youtube'),
            preserve_default=False,
        ),
    ]
