# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_course_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.Category'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course_video',
            field=models.URLField(verbose_name='Youtube Video Link'),
        ),
    ]
