# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20170223_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='course_content',
            new_name='lesson_content',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='course_title',
            new_name='lesson_title',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='course_video',
            new_name='lesson_video',
        ),
    ]
