import os

#Email settings
# TODO: Need to replace this credentials.
EMAIL_HOST = os.getenv('CODESCHOOLNEPAL_EMAIL_HOST')
EMAIL_HOST_USER = os.getenv('CODESCHOOLNEPAL_EMAIL_USER')
EMAIL_HOST_PASSWORD = os.getenv('CODESCHOOLNEPAL_EMAIL_PASSWORD')
EMAIL_PORT = os.getenv('CODESCHOOLNEPAL_EMAIL_PORT')
EMAIL_USE_TLS = os.getenv('CODESCHOOLNEPAL_EMAIL_TLS')
